# Generated by Django 2.2.1 on 2019-05-07 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Моя реклама', max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, upload_to='', verbose_name='Превью')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Рекламные публикации',
                'verbose_name': 'Рекламная публикация',
            },
        ),
    ]
