# Generated by Django 2.2.1 on 2019-05-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20190508_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='facebook_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
