# Generated by Django 2.2.1 on 2019-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20190513_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
