# Generated by Django 2.2.1 on 2019-05-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20190514_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='link',
            field=models.URLField(default='https://facebook.com/me'),
        ),
    ]
