# Generated by Django 2.2.1 on 2019-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ads_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='facebook_loaded',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='vk_loaded',
        ),
        migrations.AddField(
            model_name='ads',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='vk_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='link',
            field=models.URLField(default='https://facebook.com/me', verbose_name='Ссылка'),
        ),
    ]
